{{- if .Values.juiceShopCleanup.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: juice-cleaner
  labels:
    helm.sh/chart: {{ include "multi-juicer.chart" . }}
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'delete', 'list']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['get', 'delete']
{{- end }}
