apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juice-balancer
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "multi-juicer.chart" . }}
subjects:
  - kind: ServiceAccount
    name: juice-balancer # Name is case sensitive
roleRef:
  kind: Role
  name: juice-balancer
  apiGroup: rbac.authorization.k8s.io
