apiVersion: v1
kind: ConfigMap
metadata:
  name: juice-shop-config
  labels:
    helm.sh/chart: {{ include "multi-juicer.chart" . }}
data:
  multi-juicer.yaml: |-
{{ .Values.juiceShop.config | indent 4 }}
