on: [push, pull_request]
name: "Run Tests"
jobs:
  cleaner:
    name: Cleaner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Balancer
        run: |
          cd cleaner
          npm ci
      - name: Run Linter
        run: |
          cd cleaner
          npm run lint
      - name: Test Balancer
        run: |
          cd cleaner
          npm test -- --ci --color --verbose
  balancer:
    name: Balancer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Install & Build BalancerUI"
        run: |
          cd juice-balancer/ui
          npm ci
          npm run build
      - name: Install Balancer
        run: |
          cd juice-balancer
          npm ci
      - name: Run Linter
        run: |
          cd juice-balancer
          npm run lint
      - name: Test Balancer
        run: |
          cd juice-balancer
          npm test -- --ci --color --verbose
  progressWatchdog:
    name: ProgressWatchdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Test ProgressWatchdog"
        run: |
          cd progress-watchdog
          go vet
          go test -cover
